# Generated by Django 6.0.2 on 2026-02-20 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='quetion',
            new_name='question',
        ),
    ]
